# Buổi 02 |  05/09/2024 



In [ ]:
def f(*args):
  print(args)
  print(type(args), len(args))
  for x in args:
    print(x)
  total = 0
  for i in args:
    total += i
  print(total/len(args))
  print(type(len(args)))

f(3,4,5)

(3, 4, 5)
<class 'tuple'> 3
3
4
5
4.0
<class 'int'>


#Numpy

In [ ]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))
arr2 = arr.reshape((3,3))
print(arr2)
print(arr2*2)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1.1,2,3], [4,5,6]])
print(a)

[[1.1 2.  3. ]
 [4.  5.  6. ]]


In [ ]:
a = np.array([[1,2,3], [4,5,6]], dtype = complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [ ]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [ ]:
a = np.array([4.0,5,6])
a.dtype

dtype('float64')

In [ ]:
a = np.array([1,2,3], dtype=np.float32)
a.dtype

dtype('float32')

In [ ]:
a = np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
a = np.ones((5,3,2))
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
a = np.empty((3,3))
print(a)

[[1.e-323 2.e-323 3.e-323]
 [4.e-323 5.e-323 6.e-323]
 [7.e-323 8.e-323 9.e-323]]


In [ ]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
a = np.linspace(1,4,7)
print(a)

[1.  1.5 2.  2.5 3.  3.5 4. ]


In [ ]:
a = np.array([[1,2,3]])
print(a)

[[1 2 3]]


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[[1,2,3],[4,5,6]], 
              [[4,5,6], [7,8,9]],
             [[4,5,6], [7,8,9]]])
print(a)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]

 [[4 5 6]
  [7 8 9]]]


In [ ]:
a = np.array(range(1,13))
print(a)

b = a.reshape(3,4)
print(b)

c = a.reshape(6,2)
print(c)

d = a.reshape(2,6)
print(d)

e = a.reshape(4,3)
print(e)

f = a.reshape(12,1)
print(f)

h = a.reshape(1,12)
print(h)

g = a.reshape(-1)
print(g)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a = np.arange(20)
print('\n Array is: \n ', a)


 Array is: 
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
print('\n a[-8:17:1] = ', a[-8:17:1] )


 a[-8:17:1] =  [12 13 14 15 16]


In [ ]:
print('\n a[10:] = ', a[10:])


 a[10:] =  [10 11 12 13 14 15 16 17 18 19]


In [ ]:
a = np.arange(0,36).reshape(6,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
print(a[0,3:5])

[3 4]


In [ ]:
print(a[4:,4:])

[[28 29]
 [34 35]]


In [ ]:
print(a[:,2])

[ 2  8 14 20 26 32]


In [ ]:
print(a[2::2,::2])

[[12 14 16]
 [24 26 28]]


In [ ]:
b = np.arange(0,25).reshape(5,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
for row in b:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [ ]:
for element in b.flat:
  print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [ ]:
a = np.arange(20,60,10)
print(a)

[20 30 40 50]


In [ ]:
data = np.loadtxt('/content/drive/MyDrive/TÀI LIỆU HỌC TẬP ĐẠI HỌC 2019-2023/PYTHON & ML 02/BUỔI 02 13 04 2021/test.txt', skiprows=1)
print(data)

[[100.  11.  10. 120.]
 [ 10.  11.  15. 132.]
 [ 30.  32.  10.  43.]]


In [ ]:
data = np.loadtxt('/content/drive/MyDrive/TÀI LIỆU HỌC TẬP ĐẠI HỌC 2019-2023/PYTHON & ML 02/BUỔI 02 13 04 2021/test.txt', skiprows=1, dtype=np.int32)
print(data)

[[100  11  10 120]
 [ 10  11  15 132]
 [ 30  32  10  43]]


In [ ]:
b = np.arange(4)
print(b)

[0 1 2 3]


In [ ]:
c = a - b
print(c)

[20 29 38 47]


In [ ]:
print(b**2)

[0 1 4 9]


In [ ]:
print(10*np.sin(a))

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [ ]:
print(a<35)

[ True  True False False]


In [ ]:
print(a[a<30])

[20]


In [ ]:
print(a)
a[a>30] = 0
print(a)

[20 30 40 50]
[20 30  0  0]


In [ ]:
A = np.array([[1,1],[0,1]])
print('A = \n', A)
B = np.array([[2,0], [3,4]])
print('B = \n', B)

A = 
 [[1 1]
 [0 1]]
B = 
 [[2 0]
 [3 4]]


In [ ]:
print(A*B)

[[2 0]
 [0 4]]


In [ ]:
print(A@B)

[[5 4]
 [3 4]]


In [ ]:
print(A.dot(B))

[[5 4]
 [3 4]]


In [ ]:
a =np.random.random((2,3))
print(a)

[[0.01027476 0.85757896 0.79222711]
 [0.92733257 0.86637651 0.91839412]]


In [ ]:
print(a.sum())

4.372184017428814


In [ ]:
print(a.min())

0.010274755093177768


In [ ]:
print(a.max())

0.9273325686630128


In [ ]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [ ]:
print(b.min(axis=1))

[0 4 8]


In [ ]:
print(b.cumsum(axis=1))

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [ ]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b = a

In [ ]:
b[2:5] = 2

In [ ]:
print(b)
print(a)

[ 0  1  2  2  2  5  6  7  8  9 10 11]
[ 0  1  2  2  2  5  6  7  8  9 10 11]


In [ ]:
b is a

True

In [ ]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b = a.copy()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b[2:5] = 2

In [ ]:
print(b)
print(a)

[ 0  1  2  2  2  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b is a

False

In [ ]:
interger_data = np.array([[1,1,1],[1,1,1]])
print(interger_data)
float_data = np.array([[9,9,9], [9,9,9]])
print(float_data)

[[1 1 1]
 [1 1 1]]
[[9 9 9]
 [9 9 9]]


In [ ]:
mer = np.concatenate([interger_data, float_data], axis = 1)
print(mer)

[[1 1 1 9 9 9]
 [1 1 1 9 9 9]]


In [ ]:
 x = np.arange(1,6)
 print('First array:\n', x)
 y = np.arange(16,21)
 print('Second array:\n', y)
 print('Vertically stacked array:\n', np.vstack((x,y)))

First array:
 [1 2 3 4 5]
Second array:
 [16 17 18 19 20]
Vertically stacked array:
 [[ 1  2  3  4  5]
 [16 17 18 19 20]]


In [ ]:
 x = np.arange(1,11).reshape(2,-1)
 print('First array:\n', x)
 y = np.arange(11,21).reshape(2,-1)
 print('Second array:\n', y)
 print('Vertically stacked array:\n', np.vstack((x,y)))
 print('Concatenated 2-D array:\n', np.concatenate((x,y),axis=0))

First array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Second array:
 [[11 12 13 14 15]
 [16 17 18 19 20]]
Vertically stacked array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Concatenated 2-D array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


#Pandas

In [ ]:
import pandas as pd
pd.__version__

'1.1.5'

In [ ]:
d = {'one': pd.Series([1.,2.,3.], index=['a','b','c']), 
     'two':pd.Series([1.,2.,3.,4.], index=['a','b','c','d'])}

In [ ]:
df = pd.DataFrame(d)
print(df)

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0


In [ ]:
d1 = {'one':[1.,2.,3.,4.], 'two':[4.,5.,6.,7.]}
df1 = pd.DataFrame(d1)
print(df1)

   one  two
0  1.0  4.0
1  2.0  5.0
2  3.0  6.0
3  4.0  7.0


In [ ]:
d2 = [(1,2.,'The'), (2,3,True)]
df2 = pd.DataFrame(d2)
print(df2)

   0    1     2
0  1  2.0   The
1  2  3.0  True


In [ ]:
d3 = [{'a':1, 'b':2}, {'a':5, 'b':10, 'c': 100}]
df3 = pd.DataFrame(d3)
print(df3)

   a   b      c
0  1   2    NaN
1  5  10  100.0


In [ ]:
df = pd.DataFrame.from_dict(dict([('A', [1,2,3,4]),
                                  ('B', [4,5,6,7]),
                                  ('C', [5,6,7,8])]))
print(df)

   A  B  C
0  1  4  5
1  2  5  6
2  3  6  7
3  4  7  8


In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df.shape

(4, 3)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TÀI LIỆU HỌC TẬP ĐẠI HỌC 2019-2023/PYTHON & ML 02/BUỔI 02 13 04 2021/iris.csv')

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.head(10)

sepal_length  sepal_width  petal_length  petal_width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/TÀI LIỆU HỌC TẬP ĐẠI HỌC 2019-2023/PYTHON & ML 02/BUỔI 02 13 04 2021/iris.csv', index_col= 'sepal_length')

In [ ]:
df1.head()

sepal_width  petal_length  petal_width variety
sepal_length                                                
5.1                   3.5           1.4          0.2  Setosa
4.9                   3.0           1.4          0.2  Setosa
4.7                   3.2           1.3          0.2  Setosa
4.6                   3.1           1.5          0.2  Setosa
5.0                   3.6           1.4          0.2  Setosa

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/TÀI LIỆU HỌC TẬP ĐẠI HỌC 2019-2023/PYTHON & ML 02/BUỔI 02 13 04 2021/iris.csv', index_col='variety')

In [ ]:
df1.head()

sepal_length  sepal_width  petal_length  petal_width
variety                                                      
Setosa            5.1          3.5           1.4          0.2
Setosa            4.9          3.0           1.4          0.2
Setosa            4.7          3.2           1.3          0.2
Setosa            4.6          3.1           1.5          0.2
Setosa            5.0          3.6           1.4          0.2

In [ ]:
df1['sepal_width']

variety
Setosa       3.5
Setosa       3.0
Setosa       3.2
Setosa       3.1
Setosa       3.6
            ... 
Virginica    3.0
Virginica    2.5
Virginica    3.0
Virginica    3.4
Virginica    3.0
Name: sepal_width, Length: 150, dtype: float64

In [ ]:
df1[1:10]

sepal_length  sepal_width  petal_length  petal_width
variety                                                      
Setosa            4.9          3.0           1.4          0.2
Setosa            4.7          3.2           1.3          0.2
Setosa            4.6          3.1           1.5          0.2
Setosa            5.0          3.6           1.4          0.2
Setosa            5.4          3.9           1.7          0.4
Setosa            4.6          3.4           1.4          0.3
Setosa            5.0          3.4           1.5          0.2
Setosa            4.4          2.9           1.4          0.2
Setosa            4.9          3.1           1.5          0.1

In [ ]:
df1.loc['Setosa']

sepal_length  sepal_width  petal_length  petal_width
variety                                                      
Setosa            5.1          3.5           1.4          0.2
Setosa            4.9          3.0           1.4          0.2
Setosa            4.7          3.2           1.3          0.2
Setosa            4.6          3.1           1.5          0.2
Setosa            5.0          3.6           1.4          0.2
Setosa            5.4          3.9           1.7          0.4
Setosa            4.6          3.4           1.4          0.3
Setosa            5.0          3.4           1.5          0.2
Setosa            4.4          2.9           1.4          0.2
Setosa            4.9          3.1           1.5          0.1
Setosa            5.4          3.7           1.5          0.2
Setosa            4.8          3.4           1.6          0.2
Setosa            4.8          3.0           1.4          0.1
Setosa            4.3          3.0           1.1          0.1
Setosa            5.8          4.0           1.2          0.2
Setosa            5.7          4.4           1.5          0.4
Setosa            5.4          3.9           1.3          0.4
Setosa            5.1          3.5           1.4          0.3
Setosa            5.7          3.8           1.7          0.3
Setosa            5.1          3.8           1.5          0.3
Setosa            5.4          3.4           1.7          0.2
Setosa            5.1          3.7           1.5          0.4
Setosa            4.6          3.6           1.0          0.2
Setosa            5.1          3.3           1.7          0.5
Setosa            4.8          3.4           1.9          0.2
Setosa            5.0          3.0           1.6          0.2
Setosa            5.0          3.4           1.6          0.4
Setosa            5.2          3.5           1.5          0.2
Setosa            5.2          3.4           1.4          0.2
Setosa            4.7          3.2           1.6          0.2
Setosa            4.8          3.1           1.6          0.2
Setosa            5.4          3.4           1.5          0.4
Setosa            5.2          4.1           1.5          0.1
Setosa            5.5          4.2           1.4          0.2
Setosa            4.9          3.1           1.5          0.2
Setosa            5.0          3.2           1.2          0.2
Setosa            5.5          3.5           1.3          0.2
Setosa            4.9          3.6           1.4          0.1
Setosa            4.4          3.0           1.3          0.2
Setosa            5.1          3.4           1.5          0.2
Setosa            5.0          3.5           1.3          0.3
Setosa            4.5          2.3           1.3          0.3
Setosa            4.4          3.2           1.3          0.2
Setosa            5.0          3.5           1.6          0.6
Setosa            5.1          3.8           1.9          0.4
Setosa            4.8          3.0           1.4          0.3
Setosa            5.1          3.8           1.6          0.2
Setosa            4.6          3.2           1.4          0.2
Setosa            5.3          3.7           1.5          0.2
Setosa            5.0          3.3           1.4          0.2

In [ ]:
df1.iloc[:5]

sepal_length  sepal_width  petal_length  petal_width
variety                                                      
Setosa            5.1          3.5           1.4          0.2
Setosa            4.9          3.0           1.4          0.2
Setosa            4.7          3.2           1.3          0.2
Setosa            4.6          3.1           1.5          0.2
Setosa            5.0          3.6           1.4          0.2

In [ ]:
df1[:5]

sepal_length  sepal_width  petal_length  petal_width
variety                                                      
Setosa            5.1          3.5           1.4          0.2
Setosa            4.9          3.0           1.4          0.2
Setosa            4.7          3.2           1.3          0.2
Setosa            4.6          3.1           1.5          0.2
Setosa            5.0          3.6           1.4          0.2

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/TÀI LIỆU HỌC TẬP ĐẠI HỌC 2019-2023/PYTHON & ML 02/BUỔI 02 13 04 2021/iris.csv', index_col='variety')
df1.head()

sepal_length  sepal_width  petal_length  petal_width
variety                                                      
Setosa            5.1          3.5           1.4          0.2
Setosa            4.9          3.0           1.4          0.2
Setosa            4.7          3.2           1.3          0.2
Setosa            4.6          3.1           1.5          0.2
Setosa            5.0          3.6           1.4          0.2

In [ ]:
boolean_vector = df1['sepal_length'] > 5
print(boolean_vector)

variety
Setosa        True
Setosa       False
Setosa       False
Setosa       False
Setosa       False
             ...  
Virginica     True
Virginica     True
Virginica     True
Virginica     True
Virginica     True
Name: sepal_length, Length: 150, dtype: bool


In [ ]:
df1[boolean_vector]

sepal_length  sepal_width  petal_length  petal_width
variety                                                        
Setosa              5.1          3.5           1.4          0.2
Setosa              5.4          3.9           1.7          0.4
Setosa              5.4          3.7           1.5          0.2
Setosa              5.8          4.0           1.2          0.2
Setosa              5.7          4.4           1.5          0.4
...                 ...          ...           ...          ...
Virginica           6.7          3.0           5.2          2.3
Virginica           6.3          2.5           5.0          1.9
Virginica           6.5          3.0           5.2          2.0
Virginica           6.2          3.4           5.4          2.3
Virginica           5.9          3.0           5.1          1.8

[118 rows x 4 columns]

In [ ]:
df1.sepal_length

variety
Setosa       5.1
Setosa       4.9
Setosa       4.7
Setosa       4.6
Setosa       5.0
            ... 
Virginica    6.7
Virginica    6.3
Virginica    6.5
Virginica    6.2
Virginica    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
df1['sepal_petal'] = df1['sepal_length'] - df1.petal_length
df1.head()

sepal_length  sepal_width  petal_length  petal_width  sepal_petal
variety                                                                   
Setosa            5.1          3.5           1.4          0.2          3.7
Setosa            4.9          3.0           1.4          0.2          3.5
Setosa            4.7          3.2           1.3          0.2          3.4
Setosa            4.6          3.1           1.5          0.2          3.1
Setosa            5.0          3.6           1.4          0.2          3.6

In [ ]:
del(df1['sepal_petal'])
print(df1)

           sepal_length  sepal_width  petal_length  petal_width
variety                                                        
Setosa              5.1          3.5           1.4          0.2
Setosa              4.9          3.0           1.4          0.2
Setosa              4.7          3.2           1.3          0.2
Setosa              4.6          3.1           1.5          0.2
Setosa              5.0          3.6           1.4          0.2
...                 ...          ...           ...          ...
Virginica           6.7          3.0           5.2          2.3
Virginica           6.3          2.5           5.0          1.9
Virginica           6.5          3.0           5.2          2.0
Virginica           6.2          3.4           5.4          2.3
Virginica           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [ ]:
df1.pop('sepal_length')

variety
Setosa       5.1
Setosa       4.9
Setosa       4.7
Setosa       4.6
Setosa       5.0
            ... 
Virginica    6.7
Virginica    6.3
Virginica    6.5
Virginica    6.2
Virginica    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
print(df1)

           sepal_width  petal_length  petal_width
variety                                          
Setosa             3.5           1.4          0.2
Setosa             3.0           1.4          0.2
Setosa             3.2           1.3          0.2
Setosa             3.1           1.5          0.2
Setosa             3.6           1.4          0.2
...                ...           ...          ...
Virginica          3.0           5.2          2.3
Virginica          2.5           5.0          1.9
Virginica          3.0           5.2          2.0
Virginica          3.4           5.4          2.3
Virginica          3.0           5.1          1.8

[150 rows x 3 columns]


In [ ]:
df1.assign(ratio=df1['sepal_width']/df1['petal_length']).head()

sepal_width  petal_length  petal_width     ratio
variety                                                  
Setosa           3.5           1.4          0.2  2.500000
Setosa           3.0           1.4          0.2  2.142857
Setosa           3.2           1.3          0.2  2.461538
Setosa           3.1           1.5          0.2  2.066667
Setosa           3.6           1.4          0.2  2.571429

In [ ]:
df1.assign(ratio = lambda x: x['sepal_width']/x['petal_length']).head()

sepal_width  petal_length  petal_width     ratio
variety                                                  
Setosa           3.5           1.4          0.2  2.500000
Setosa           3.0           1.4          0.2  2.142857
Setosa           3.2           1.3          0.2  2.461538
Setosa           3.1           1.5          0.2  2.066667
Setosa           3.6           1.4          0.2  2.571429

In [ ]:
for idx, row in df1.iterrows():
  print(idx)
  for item in row:
    print('Item:', item)
  break

Setosa
Item: 3.5
Item: 1.4
Item: 0.2


In [ ]:
matrix = np.arange(1, 17).reshape(4,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
df = pd.DataFrame(matrix, columns = list('abcd'))
print(df)

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16


In [ ]:
new_df = df.apply(lambda x: x + 10)
print(new_df)

    a   b   c   d
0  11  12  13  14
1  15  16  17  18
2  19  20  21  22
3  23  24  25  26


In [ ]:
new_df = df.apply(lambda x: x +5, axis = 1)
print(new_df)

    a   b   c   d
0   6   7   8   9
1  10  11  12  13
2  14  15  16  17
3  18  19  20  21


In [ ]:
def squareData(x):
  return x*x

In [ ]:
new_df = df.apply(squareData)
print(new_df)

     a    b    c    d
0    1    4    9   16
1   25   36   49   64
2   81  100  121  144
3  169  196  225  256


In [ ]:
new_df = df.apply(squareData, axis = 1)
print(new_df)

     a    b    c    d
0    1    4    9   16
1   25   36   49   64
2   81  100  121  144
3  169  196  225  256


In [ ]:
new_df = df['a'].apply(squareData)
print(new_df)

0      1
1     25
2     81
3    169
Name: a, dtype: int64


In [ ]:
new_df = df.apply(np.square)
print(new_df)

     a    b    c    d
0    1    4    9   16
1   25   36   49   64
2   81  100  121  144
3  169  196  225  256


In [ ]:
new_df = df.apply(np.square, axis = 1)
print(new_df)

     a    b    c    d
0    1    4    9   16
1   25   36   49   64
2   81  100  121  144
3  169  196  225  256


In [ ]:
new_df = df.apply(np.sum)
print(new_df)

a    28
b    32
c    36
d    40
dtype: int64


In [ ]:
new_df = df.apply(np.sum, axis = 1)
print(new_df)

0    10
1    26
2    42
3    58
dtype: int64


In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/TÀI LIỆU HỌC TẬP ĐẠI HỌC 2019-2023/PYTHON & ML 02/BUỔI 02 13 04 2021/iris.csv', index_col='variety')
df1.head()

sepal_length  sepal_width  petal_length  petal_width
variety                                                      
Setosa            5.1          3.5           1.4          0.2
Setosa            4.9          3.0           1.4          0.2
Setosa            4.7          3.2           1.3          0.2
Setosa            4.6          3.1           1.5          0.2
Setosa            5.0          3.6           1.4          0.2

In [ ]:
df1.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [ ]:
ipl_data = {'Team': ['UIT', 'BK', 'KHTN', 'IU', 'NV', 'KTX_A', 'KTX_B', 'UIT', 'IU'],
            'Rank': [1,2,3,4,5,6,7,1,4],
            'Year': [15, 90, 80, 70, 85, 20, 15, 15,10],
            'Points': [872, 781, 659, 458, 287, 912, 458,234,456]}

In [ ]:
df = pd.DataFrame(ipl_data)
print(df)

    Team  Rank  Year  Points
0    UIT     1    15     872
1     BK     2    90     781
2   KHTN     3    80     659
3     IU     4    70     458
4     NV     5    85     287
5  KTX_A     6    20     912
6  KTX_B     7    15     458
7    UIT     1    15     234
8     IU     4    10     456


In [ ]:
df.groupby('Team').groups

{'BK': [1], 'IU': [3, 8], 'KHTN': [2], 'KTX_A': [5], 'KTX_B': [6], 'NV': [4], 'UIT': [0, 7]}

In [ ]:
grouped = df.groupby('Year')
for name, group in grouped:
  print(name)
  print(group)

10
  Team  Rank  Year  Points
8   IU     4    10     456
15
    Team  Rank  Year  Points
0    UIT     1    15     872
6  KTX_B     7    15     458
7    UIT     1    15     234
20
    Team  Rank  Year  Points
5  KTX_A     6    20     912
70
  Team  Rank  Year  Points
3   IU     4    70     458
80
   Team  Rank  Year  Points
2  KHTN     3    80     659
85
  Team  Rank  Year  Points
4   NV     5    85     287
90
  Team  Rank  Year  Points
1   BK     2    90     781


In [ ]:
grouped = df.groupby('Year')
grouped.get_group(15)

Team  Rank  Year  Points
0    UIT     1    15     872
6  KTX_B     7    15     458
7    UIT     1    15     234

In [ ]:
grouped = df.groupby('Year')
grouped['Points'].agg(np.mean)

Year
10    456.000000
15    521.333333
20    912.000000
70    458.000000
80    659.000000
85    287.000000
90    781.000000
Name: Points, dtype: float64

In [ ]:
grouped = df.groupby('Team')
grouped.agg(np.size)

Rank  Year  Points
Team                     
BK        1     1       1
IU        2     2       2
KHTN      1     1       1
KTX_A     1     1       1
KTX_B     1     1       1
NV        1     1       1
UIT       2     2       2

In [ ]:
grouped = df.groupby('Team')
grouped['Points'].agg([np.sum, np.mean, np.std])

sum  mean         std
Team                         
BK      781   781         NaN
IU      914   457    1.414214
KHTN    659   659         NaN
KTX_A   912   912         NaN
KTX_B   458   458         NaN
NV      287   287         NaN
UIT    1106   553  451.134126

In [ ]:
df.groupby('Team').filter(lambda x: len(x) >= 2)

Team  Rank  Year  Points
0  UIT     1    15     872
3   IU     4    70     458
7  UIT     1    15     234
8   IU     4    10     456

# Bài tập Numpy

##ViPy_061_np1

Nhập 1 số n từ bàn phím, tạo 1 numpy array chạy từ 0 -> n - 1.

Thay thế các giá trị lẻ bằng -1. Sau đó in ra màn hình.

Input Format

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Constraints

.

Output Format

[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

In [ ]:
import numpy as np
n = int(input())

A = np.arange(n)
for i in range(len(A)):
  if A[i] % 2 != 0:
    A[i] = -1

print(A)

10
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


##ViPy_061_np2

Nghĩ ra cách nhanh nhất để tạo ra numpy array sau:

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
       
Input Format

.

Constraints

.

Output Format

.

In [ ]:
import numpy as np

A = np.arange(10).reshape(2,-1)
B = np.ones((2,5), dtype='int64')
C = np.concatenate([A,B], axis = 0)

print(C)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##ViPy_061_np3

Tìm phần tử chung giữa 2 mãng. Bằng cách sử dụng google để tìm hàm phù hợp.

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

Output

array([2, 4])

Input Format

.

Constraints

.

Output Format

.

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a, b))

[2 4]


##ViPy_061_np4

Xuất ra tất cả các phần tử nằm trong khoảng từ 5 -> 10

a = np.array([2, 6, 1, 9, 10, 3, 27])

output:

[6, 9, 10]

Input Format

.

Constraints

.

Output Format

.

In [ ]:
import numpy as np

a = np.array([2,6,1,9,10,3,27])

print(a[np.logical_and(a > 4, a < 11)])

[ 6  9 10]


##ViPy_061_np5

Cho numpy array như sau:

arr = np.arange(9).reshape(3,3)
Sử dụng google để tìm cách swap 2 column với nhau

Input Format

.

Constraints

.

Output Format

.

In [ ]:
arr = np.arange(9).reshape(3,3)
print('Orginal Array: \n', arr)

arr[:,[0,2]] = arr[:,[2,0]]
print('After swapping:\n', arr)

Orginal Array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
After swapping:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


##ViPy_061_np6

Cho dữ liệu các đặc trưng của loại hoa Iris theo đường dẫn sau:

https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

sử dụng genfromtxt để đọc dữ liệu thành dạng numpy matrix kích thước số dòng x 4 (4 cột đầu tiên)

Ví dụ:

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       ....
       
Input Format

.

Constraints

.

Output Format

.

In [ ]:
import numpy as np 
A = np.genfromtxt('/content/drive/MyDrive/TÀI LIỆU HỌC TẬP ĐẠI HỌC 2019-2023/PYTHON & ML 02/BUỔI 02 13 04 2021/iris.data', skip_header=0, filling_values=0, delimiter=',', usecols=range(0,4))
print(A)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

##ViPy_061_np7

Với dữ liệu ở đường dẫn sau.

https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Hãy tính giá trị mean, median, standard deviation của cột đầu tiên sepallength

Input Format

.

Constraints

.

Output Format

.

In [ ]:
import numpy as np 
A = np.genfromtxt('/content/drive/MyDrive/TÀI LIỆU HỌC TẬP ĐẠI HỌC 2019-2023/PYTHON & ML 02/BUỔI 02 13 04 2021/iris.data', skip_header=0, filling_values=0, delimiter=',', usecols=range(0,1))
mean = np.mean(A)
median = np.median(A)
standard_deviation = np.std(A)

print('A =\n', A)
print('mean =', mean)
print('median =', median)
print('standard deviation =', standard_deviation)      

A =
 [5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
mean = 5.843333333333334
median = 5.8
standard deviation = 0.8253012917851409


In [ ]:
import numpy as np 
B = np.genfromtxt('/content/drive/MyDrive/TÀI LIỆU HỌC TẬP ĐẠI HỌC 2019-2023/PYTHON & ML 02/BUỔI 02 13 04 2021/iris.data', skip_header=0, filling_values=0, delimiter=',')
mean = np.mean(B[:,0:1])
median = np.median(B[:,0:1])
standard_deviation = np.std(B[:,0:1])

print('B =\n', B)
print('mean =', mean)
print('median =',median)
print('standard deviation =',standard_deviation)  

B =
 [[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  